name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle wrapper validation (non-fatal)
        uses: gradle/actions/wrapper-validation@v3
        continue-on-error: true
        timeout-minutes: 3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug --stacktrace

      - name: Unit tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: testDebugUnitTest --stacktrace

      - name: Lint
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lintDebug --stacktrace
