name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Gradle wrapper validation (non-fatal)
        uses: gradle/actions/wrapper-validation@v3
        continue-on-error: true
        timeout-minutes: 3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: false

      - name: Build
        run: ./gradlew assembleDebug --stacktrace

      - name: Unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Lint
        run: ./gradlew lintDebug --stacktrace
