name: Android CI

on:
  push:
    branches: [ "master", "main", "develop" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/codeql.yml'
  pull_request:
    branches: [ "master", "main", "develop" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Run lint checks
      run: ./gradlew lint

    - name: Run unit tests
      run: ./gradlew test

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          app/build/reports/
          build/reports/

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v3
      with:
        name: apk-artifacts
        path: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*.apk

  test:
    name: Run Instrumented Tests
    runs-on: macos-latest  # Use macOS for hardware acceleration
    strategy:
      matrix:
        api-level: [29, 31, 33]  # Test on multiple API levels
        target: [google_apis]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}-${{ matrix.target }}

    - name: Create AVD and run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        script: ./gradlew connectedAndroidTest

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports-api-${{ matrix.api-level }}
        path: |
          app/build/reports/androidTests/
          app/build/outputs/androidTest-results/